### ISSUE TITLE
用OpenCV找不到opencv2/opencv.hpp头文件

### ISSUE THREAD

**Issue by banana16314** [xmake-io/xrepo-cmake#15]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

### 描述讨论详情
请在这描述你需要讨论的话题详情。
cmake ..可以发现opencv，但是make的时候，fatal error: opencv2/opencv.hpp: 没有那个文件或目录

### CMakeLists.txt部分：
#指定cmake的最小版本
cmake_minimum_required(VERSION 3.4.1)

project(demo)

set(CMAKE_CXX_FLAGS "-std=c++11")

#Download xrepo.cmake if not exists in build directory.
if(NOT EXISTS "${CMAKE_BINARY_DIR}/xrepo.cmake")
    message(STATUS "Downloading xrepo.cmake from https://github.com/xmake-io/xrepo-cmake/")
    # mirror https://cdn.jsdelivr.net/gh/xmake-io/xrepo-cmake@main/xrepo.cmake
    file(DOWNLOAD "https://raw.githubusercontent.com/xmake-io/xrepo-cmake/main/xrepo.cmake"
                  "${CMAKE_BINARY_DIR}/xrepo.cmake"
                  TLS_VERIFY ON)
endif()

include(${CMAKE_BINARY_DIR}/xrepo.cmake)

xrepo_package("spdlog")
xrepo_package("opencv 4.5.4")

### 在build目录下执行cmake ..的输出如下：
-- xmake command: /usr/bin/xmake
-- xrepo fetch --json: OFF
-- xrepo: spdlog already installed, using cached variables
-- xrepo: spdlog_INCLUDE_DIR /home/XXX/.xmake/packages/s/spdlog/v1.9.2/237d31e048844016b30f5b496e1385d7/include
-- xrepo: spdlog_LINK_DIR /home/XXX/.xmake/packages/s/spdlog/v1.9.2/237d31e048844016b30f5b496e1385d7/lib
-- xrepo: opencv 4.5.4 already installed, using cached variables
-- xrepo: opencv_INCLUDE_DIR /home/XXX/.xmake/packages/o/opencv/4.5.4/e610c461a5844179809cd993282550cb/include
-- xrepo: opencv_LINK_DIR /home/XXX/.xmake/packages/o/opencv/4.5.4/e610c461a5844179809cd993282550cb/lib
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hcq/文档/test/cmakeSift/build

### 执行make的时候提示：
src/ImgRegistration.h:4:10: fatal error: opencv2/opencv.hpp: 没有那个文件或目录

**Comment by waruqi** [comment]
> -- xrepo: opencv_INCLUDE_DIR /home/XXX/.xmake/packages/o/opencv/4.5.4/e610c461a5844179809cd993282550cb/include

到这个目录，找下对应文件在哪里 ，tree 下

**Comment by banana16314** [comment]
...include/opencv4/opencv2
---aruco
---aruco.hpp
---barcode.hpp
...

**Comment by waruqi** [comment]
可以用 xrepo fetch opencv 命令看下，按理 includedirs 已经包含 opencv4 子目录了，但是你这检测到没有

你这个 cmakelists.txt 也没贴全，我也看不出什么，建议走 xrepo_target_packages 接口，而不是 cmake find_package。。

cmake 的 find_package 不一定能给你附带上 opencv4 子目录

**Comment by banana16314** [comment]
完整的CMakeLists.txt是这样的：
#指定cmake的最小版本
cmake_minimum_required(VERSION 3.4.1)

#[[
设置项目名称，它会引入两个变量 demo_BINARY_DIR 和 demo_SOURCE_DIR，
同时，cmake 自动定义了两个等价的变量 PROJECT_BINARY_DIR 和 PROJECT_SOURCE_DIR。
]]
project(demo)

#指定c++版本
# specify the C++ standard
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED True)

#Download xrepo.cmake if not exists in build directory.
if(NOT EXISTS "${CMAKE_BINARY_DIR}/xrepo.cmake")
    message(STATUS "Downloading xrepo.cmake from https://github.com/xmake-io/xrepo-cmake/")
    # mirror https://cdn.jsdelivr.net/gh/xmake-io/xrepo-cmake@main/xrepo.cmake
    file(DOWNLOAD "https://raw.githubusercontent.com/xmake-io/xrepo-cmake/main/xrepo.cmake"
                  "${CMAKE_BINARY_DIR}/xrepo.cmake"
                  TLS_VERIFY ON)
endif()

#Include xrepo.cmake so we can use xrepo_package function.
include(${CMAKE_BINARY_DIR}/xrepo.cmake)

xrepo_package("spdlog")
xrepo_package("opencv 4.5.4")


#头文件目录，将指定目录添加到编译器的头文件搜索路径之下，指定的目录被解释成当前源码路径的相对路径。
include_directories(
    ${CMAKE_CURRENT_SOURCE_DIR}/src #自己写的头文件所在目录

)

#查找c++源文件
file(GLOB_RECURSE CPP_SOURCE_FILES 
      "${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp"
      "${CMAKE_CURRENT_SOURCE_DIR}/src/*.h"
) #GLOB_RECURSE 查找包括子目录


add_executable(mainWorker ${CPP_SOURCE_FILES})
target_link_libraries(mainWorker spdlog opencv)

**Comment by banana16314** [comment]
### CMakeLists.txt 我改成下面了：
add_executable(mainWorker ${CPP_SOURCE_FILES})
#target_link_libraries(mainWorker spdlog opencv)
xrepo_target_packages(
    mainWorker
    spdlog opencv
)
make的时候报的错误是：
.../.xmake/packages/o/opencv/4.5.4/e610c461a5844179809cd993282550cb/include/opencv4/opencv2/opencv.hpp:48:10: fatal error: opencv2/opencv_modules.hpp: 没有那个文件或目录
   48 | #include "opencv2/opencv_modules.hpp"

**Comment by waruqi** [comment]
说明 opencv2/opencv.hpp 已经找到了，includedir 没问题，至于 opencv_modules.hpp 有没有，自己找下路径

**Comment by banana16314** [comment]
.../.xmake/packages/o/opencv/4.5.4/e610c461a5844179809cd993282550cb/include/opencv4/opencv2/ 这个目录下面opencv.hpp和opencv_modules.hpp是挨着的，opencv.hpp下面一个文件就是opencv_modules.hpp

**Comment by waruqi** [comment]
那我不知道，只要 includedirs 和路径没问题，那跟 xmake 没啥关系了
