### ISSUE TITLE
如何设置并行编译线程数

### ISSUE THREAD

**Issue by nqf** [xmake-io/xrepo-cmake#23]
### 你在什么场景下需要该功能？

目前我执行cmake ..,   xrepo_package 会自动安装依赖， 但是它使用默认24 个线程编译， 我想要设置编译线程数， 该怎么做

### 描述可能的解决方案

通过配置文件？

**Comment by waruqi** [comment]
提个 pr 过来，加个参数配置 jobs number，传递到 xrepo install -jN
