### ISSUE TITLE
xrepo_package 为什么不从我本地仓库中查找安装包信息

### ISSUE THREAD

**Issue by nqf** [xmake-io/xrepo-cmake#27]
### Xmake Version

2.6.8

### Operating System Version and Architecture

centos7

### Describe Bug

我执行下面命令增加一个私有仓库 到本地， 但是 `xrepo_package` 似乎不会从本地仓库中查找软件包， 如果我增加全局仓库它可以工作
`xmake repo -a private_repo xxxxxxxgithub/xmake-repo.git`

### Expected Behavior

可以从本地仓库中查找软件包信息

**Comment by waruqi** [comment]
`xmake repo` 仅用于 xmake.lua 所有本地工程中仓库追加，你都用了 xrepo-cmake 了，在自己 cmake 工程中，没有任何 xmake 工程存在，根本缓存不了本地信息，你只能用 xrepo 访问全局仓库。。

因为 cmake 编译不归 xmake 管，这个时候，cmake 只能调用 xrepo 独立的包管理命令，没有 xmake 工程什么事情。

**Comment by nqf** [comment]
>
非常感谢

还有一个问题， 为什么 xmake 不能删除  build-artifacts  xmake-repo builtin-repo， 因为我已经添加我的私有仓库到全局， 所以我想删除其它仓库

```
☁  build [master] ⚡  xrepo rm-repo build-artifacts 
error: repository(build-artifacts): not found!
error: execv(xmake repo --remove --global build-artifacts) failed(255)
☁  build [master] ⚡  xrepo rm-repo xmake-repo              
error: repository(xmake-repo): not found!
error: execv(xmake repo --remove --global xmake-repo) failed(255)
```

**Comment by waruqi** [comment]
没必要删，你添加了自己的仓库，包都会优先从你的仓库中找，只有找不到 才会走内置仓库。

**Comment by nqf** [comment]
> 没必要删，你添加了自己的仓库，包都会优先从你的仓库中找，只有找不到 才会走内置仓库。

如果我设置多个 私有仓库， 它的查找顺序是什么？  比如 add private a， add private b， 它的查找顺序 是 `a仓库->b 仓库->内置仓库 `吗？

**Comment by waruqi** [comment]
> > 没必要删，你添加了自己的仓库，包都会优先从你的仓库中找，只有找不到 才会走内置仓库。
> 
> 如果我设置多个 私有仓库， 它的查找顺序是什么？ 比如 add private a， add private b， 它的查找顺序 是 `a仓库->b 仓库->内置仓库 `吗？

最后添加的优先找
