### ISSUE TITLE
Add an option to bootstrap xmake when not found

### ISSUE THREAD

**Issue by mrexodia** [xmake-io/xrepo-cmake#6]
Currently you use `find_package` to find xmake, but it would be cool if this script automatically bootstraps a version of xmake in the `${CMAKE_BINARY_DIR}` and uses that so the user doesn't have to install it.

**Comment by waruqi** [comment]
ok, I wll consider to add it.

**Comment by waruqi** [comment]
I have added it, `cmake -DXREPO_BOOTSTRAP_XMAKE=ON`

Now I don't have it enabled by default, because I need to wait for the release of xmake 2.6.3 to better support xrepo-cmake.

**Comment by mrexodia** [comment]
Awesome, thanks a lot! I'll try to integrate it into cmkr this weekend ^^

**Comment by waruqi** [comment]
I have enabled this feature by default. and please update xmake to v2.6.3
